version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../web-src:/var/www/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: php7.4-dockerfile
    image: custom-php7.4
    expose:
      - 9003 # for xdebug
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../web-src:/var/www/html
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini # for xdebug
      - ./config/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini # for error reporting
