version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../web-src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: php7.4-dockerfile
    image: custom-php7.4
    expose:
      - 9003 # for xdebug
    volumes:
      - ../web-src:/var/www/html
